name: aflstatsrecordingapp1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.4 # For storing images
  cached_network_image: ^3.3.1 # For efficient image loading
  provider: ^6.1.1 # For state management
  intl: ^0.19.0 # For date formatting
  path_provider: ^2.1.2
  pdf: ^3.10.7
  share_plus: ^7.2.2
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/afl.png"

flutter_native_splash:
  color: "#8B0000"
  image: assets/afl.png
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/afl.png
    - assets/afl_banner.jpg
    - assets/background/6.jpg

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-VariableFont_wght.ttf
